### ISSUE TITLE
Curve25519 support

### ISSUE THREAD

**Issue by packerdbell** [stealth/opmsg#13]
Hi,

Great work on opmsg!  I was wondering if there are plans to support other EC such as Curve25519, Curve1174, M-511 or E-521?

Thanks!

**Comment by elimpnick** [comment]
My guess is that it supports whatever "openssl ecparam -list_curves " supports.  If you use OpenSSL ≥ 1.1.0, Curve25519 should be supported.

**Comment by stealth** [comment]
Indeed. I have to check whether the 25519 is supported by means of the EVP API. The problem is that it needs different signing algos than the traditional curves that use ECDSA. If thats covered by the new versions, I should have little problems adding it.
If you fear about the strengths of the curves in use, check out the cross-domain ECDH feature.
Also note that you can use the same curve thats used in bitcoin, which seems to be trusted by quite some people.

**Comment by packerdbell** [comment]
Cool thanks!
