### ISSUE TITLE
opmsg decryption output msg

### ISSUE THREAD

**Issue by naveedpash** [stealth/opmsg#20]
Hey guys,

Great program!

I'm trying to use opmsg to decrypt my gmail password and source it into mutt. I can't use gpg (don't ask; very stupid reasons) but on my old system I used
`source "gpg -e -R naveedpash@gmail.com <filename> |"`
which would feed the password right to mutt without printing it to file or standard output.

This is great because I don't want dangling tmp files and I don't want to type out the password everytime in mutt.

However, when opmsg decrypts a file, it also outputs some messages. Therefore I can't use 

`source "opmsg -D -i <filename> |`

Is there a way/options to surpress output messages during decryption so I can just get my password?

**Comment by stealth** [comment]
I dont know if encrypting passwords makes much sense, as  opmsg wouldnt
require a passphrase to decrypt it. But anyway, the status messages of opmsg
go to stderr, while the plain decrypted data is to stdout. So, by redirecting fd 2 to
/dev/null, you will just get the pure data:

opmsg -D < x.opmsg 2>/dev/zero

which should equal to

source "opmsg -D -i <filename> 2>/dev/zero|

if mutt is using sh -c to execute it. otherwise you would also need to prepend
sh -c by yourself, but make sure <filename> will never contain shell escape characters.
